language: node_js
node_js:
- node
dist: trusty
cache: npm
branches:
  only:
  - master
install:
- npm ci
script:
- npm test
after_success: npm run coverage
deploy:
  provider: npm
  email: rproenza86@gmail.com
  api_key:
    secure: sPqDnrdJEEKZxZqWGApTYz3B6aprvq2Zamu7hZhz6ljzfyMP2syrLqZtsz62g92fdtylyhuqjBVdqOBUAEMZNL7V1FouWoT8iObzNkWmzuJ+1UVIhuFynfhhG6bbvT7isDGypvJjDscz9BUXzBC92W2BfXFOuU/ZYHCa+NXPWnMEvA5k75gyFNl63ee3U3XPkE0xl88XGYWFkkkcunlCCbMFecFsZS/h6SDviDus9Pz7xyjzWlECakp31qlPXKLPH5b5KuXRbCM7KRZbJx9nSmSlupbArRAZ24N57yqZdtOSUuipULdFbBfaYzLIvurmphHU8A+LDn60g0UhjOzLAN4XOgZ4VssXQAePHfNNT29Pzb1IuPyVisjjhaPvhA2UIA/Dk2TY04MB0Wzo04xl8I5xdobdwN5rEE5ycZa8Yrkeigfs6zfZRAQRr6VIkT6fQTgzDk/5nvjP/zd4DSIjBw5zZUHe6dsY1M6EH+OrHZqfRCLtwJmwSa9ayifUjoNIuz1iVyWvG8GJMNJrQ0hOhRNeAXFop01C9XXNsPpezMsUWZ2DT2j5ZYzDnlx2bEMhVK6LGcZx8U4KdbE+1D5mewXVVfoLMPKr95RHMp5K533emMULedQGrKVhQlLwMKfOrC5UoykfhQlrVayIyue/xu6F/n/B/kgEwa5cSJq2p1g=
  on:
    branch: master
COVERALLS_REPO_TOKEN:
  secure: ejabl798zqJQJGD0ICPylIS/8pRNtBBvI5L0l9eXPrJFvEL+r5YezT10iG5w+Z8h59kt6OIskh+nI5omhFPB1slog6AF2RQzyGeoRoIZnXIzMpr/5Dj7ATjBGM70cOHNRI2xPWxESXu4NNNZ0sYeDSRZF2LIJ7X8d+tJEl9GcAqJUTZTyQ+mPPAcYvSIc3n6EoQZt0jnSYfQA0E3Xxpw0a7YkR8B9qKT8dY6zEOtposuizdeLnDym/qbJ8rqwUfiElJ/Vs0Xxic2vedfeccMvRglOU0a+3+f7B5b33URWGMO9PlpEV3w5bqcZFtO3pD5cxaMrC64biJWgu81YHgKBV3Y8shvWzJTGdeZRAh1oGDOsbiOjOr4eXk5C5YO2s2ESEezszntZoudpHDmxck55oQOp+8vGU4A7/lN3gira9+plyM4YAOcHzAL/A/OJCJLo/CuLJFiSeLvC1PhT/g6EQ3ZdfHzhU3RdueDITgvVDBgAO89rhxXe3RkesRvsNLivlkpUQsCXX5dyrR/9UipAybluXmp/7+zy6aiNTtoTFT2FS55YAqJr/HaBww9YawT2LEu9u2TaA3ze01vu04E20XuU8sb937K9w71ZtHt1RcFFthcBeS3fkOliuqQ/Oxvd1Or5I4nKRPPjlWfGnxHJR9j6qBScJvwUXhxTaMD1qg=
