language: node_js
node_js:
  - "node"
dist: trusty
cache: npm
branches:
  only:  # Creates a whitelist.  Any branch not in this list will not build.
    - master 
install:
  - npm ci
script:
  - npm test
after_success: npm run coverage